name: Deploy

on:
    push:
        branches:
            - main

env:
    DEPLOY_MODE: prod
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 14.19.0

            - uses: actions/cache@v3
              with:
                  path: ./node_modules
                  key: ${{ runner.os }}-modules-${{ hashFiles('./yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules

            - name: INSTALL
              run: yarn install

            - name: DEPLOY
              run: yarn deploy
